# Generated by Django 4.2.15 on 2024-08-19 20:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('fecha_ingreso', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', related_query_name='RELACION_FK_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
