# Generated by Django 4.2.15 on 2024-08-20 00:37

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('es_correcta', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Opcion',
                'verbose_name_plural': 'Opciones',
                'db_table': 'Opcion',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='cuestionario',
            options={'ordering': ['-id'], 'verbose_name': 'Cuestionario', 'verbose_name_plural': 'Cuestionarios'},
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='titulo',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='cuestionario',
            table='Cuestionario',
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='cuestionario.cuestionario')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'db_table': 'Resultado',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to=settings.AUTH_USER_MODEL)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='cuestionario.opcion')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'Respuesta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('texto', ckeditor.fields.RichTextField()),
                ('opciones', models.ManyToManyField(blank=True, help_text='Opciones', related_name='RELACION_%(app_label)s_%(class)s', related_query_name='RELACION_MM_%(app_label)s_%(class)s', to='cuestionario.opcion', verbose_name='Opcion')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'Pregunta',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='preguntas',
            field=models.ManyToManyField(blank=True, help_text='Preguntas', related_name='RELACION_%(app_label)s_%(class)s', related_query_name='RELACION_MM_%(app_label)s_%(class)s', to='cuestionario.pregunta', verbose_name='Pregunta'),
        ),
    ]
