# Generated by Django 4.2.15 on 2024-08-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0003_tags_cuestionario_dificultad_cuestionario_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='preguntas',
            field=models.ManyToManyField(blank=True, help_text='Preguntas', related_name='RELACION_CUESTIONARIO_PREGUNTA', related_query_name='RELACION_MM_CUESTIONARIO_PREGUNTA', to='cuestionario.pregunta', verbose_name='Pregunta'),
        ),
    ]
