import pathlib
#○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○#
# Funcion que guarda la ruta de la img
#○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○#
def guardar_imagen(instance, filename):
    fpath = pathlib.Path(filename)
    name = (instance.username).replace(":","")
    #new_fname = str(instance.nombre)
    return f"static/user/img-{instance.username}/{name}{fpath.suffix}"
# ○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○#
#         Lenguajes
Lenguajes = (
    ('America', (
        ('brazilian_portuguese', 'Portugués brasileño'),
        ('canadian_french', 'Francés canadiense'),
        ('english', 'Inglés'),
        ('french_creole', 'Criollo francés'),
        ('haitian_creole', 'Criollo haitiano'),
        ('navajo', 'Navajo'),
        ('quechua', 'Quechua'),
        ('spanish', 'Español'),
    )),
    ('Western Europe', (
        ('catalan', 'Catalán'),
        ('danish', 'Danés'),
        ('dutch', 'Holandés'),
        ('faroese', 'Feroés'),
        ('finnish', 'Finlandés'),
        ('flemish', 'Flamenco'),
        ('french', 'Francés'),
        ('german', 'Alemán'),
        ('greek', 'Griego'),
        ('icelandic', 'Islandés'),
        ('italian', 'Italiano'),
        ('norwegian', 'Noruego'),
        ('portuguese', 'Portugués'),
        ('spanish', 'Español'),
        ('swedish', 'Sueco'),
        ('uk_english', 'Inglés británico / Inglés británico'),
    )),
    ('Central & Eastern Europe', (
        ('belarusian', 'Bielorruso'),
        ('bosnian', 'Bosnio'),
        ('bulgarian', 'Búlgaro'),
        ('croatian', 'Croata'),
        ('czech', 'Checo'),
        ('estonian', 'Estonio'),
        ('hungarian', 'Húngaro'),
        ('latvian', 'Letón'),
        ('lithuanian', 'Lituano'),
        ('macedonian', 'Macedonio'),
        ('polish', 'Polaco'),
        ('romanian', 'Rumano'),
        ('russian', 'Ruso'),
        ('serbian', 'Serbio'),
        ('slovak', 'Eslovaco'),
        ('slovenian', 'Esloveno'),
        ('turkish', 'Turco'),
        ('ukrainian', 'Ucraniano'),
    )),
    ('Africa', (
        ('amharic', 'Amárico (Etiopía)'),
        ('dinka', 'Dinka (Sudán)'),
        ('ibo', 'Ibo (Nigeria)'),
        ('kirundi', 'Kirundi'),
        ('mandinka', 'Mandinka'),
        ('nuer', 'Nuer (Nilo-Sahariano)'),
        ('oromo', 'Oromo (Etiopía)'),
        ('kinyarwanda', 'Kinyarwanda'),
        ('shona', 'Shona (Zimbabue)'),
        ('somali', 'Somalí'),
        ('swahili', 'Suajili'),
        ('tigrigna', 'Tigrigna (Etiopía)'),
        ('wolof', 'Wolof'),
        ('xhosa', 'Xhosa'),
        ('yoruba', 'Yoruba'),
        ('zulu', 'Zulú'),
    )),
    ('Middle East', (
        ('arabic', 'Árabe'),
        ('dari', 'Dari'),
        ('farsi', 'Persa'),
        ('hebrew', 'Hebreo'),
        ('kurdish', 'Kurdo'),
        ('pashtu', 'Pastún'),
        ('punjabi', 'Punyabí'),
        ('urdu_pakistan', 'Urdu (Pakistán)'),
    )),
    ('Central Asia', (
        ('armenian', 'Armenio'),
        ('azerbaijani', 'Azerbaiyano'),
        ('georgian', 'Georgiano'),
        ('kazakh', 'Kazajo'),
        ('mongolian', 'Mongol'),
        ('turkmen', 'Turcomano'),
        ('uzbek', 'Uzbeko'),
    )),
    ('Southeast Asia', (
        ('bengali', 'Bengalí'),
        ('cham', 'Cham'),
        ('chamorro_guam', 'Chamorro (Guam)'),
        ('gujarati_india', 'Guyaratí (India)'),
        ('hindi', 'Hindi'),
        ('indonesian', 'Indonesio'),
        ('khmer_cambodia', 'Jemer (Camboya)'),
        ('kmhmu_laos', 'Kmhmu (Laos)*'),
        ('korean', 'Coreano'),
        ('laotian', 'Laosiano'),
        ('malayalam', 'Malayalam'),
        ('malay', 'Malayo'),
        ('marathi_india', 'Marathi (India)'),
        ('marshallese', 'Marshalés'),
        ('nepali', 'Nepalí'),
        ('sherpa', 'Sherpa*'),
        ('tamil', 'Tamil'),
        ('thai', 'Tailandés'),
        ('tibetan', 'Tibetano'),
        ('trukese_micronesia', 'Trukés (Micronesia)'),
        ('vietnamese', 'Vietnamita'),
    )),
    ('Far East', (
        ('amoy', 'Amoy'),
        ('burmese', 'Birmano'),
        ('cantonese', 'Cantonés'),
        ('chinese', 'Chino'),
        ('chinese_simplified', 'Chino Simplificado'),
        ('chinese_traditional', 'Chino Tradicional'),
        ('chiu_chow', 'Chiu Chow'),
        ('chow_jo', 'Chow Jo'),
        ('fukienese', 'Fukienese'),
        ('hakka_china', 'Hakka (China)'),
        ('hmong', 'Hmong'),
        ('hainanese', 'Hainanés'),
        ('japanese', 'Japonés'),
        ('mandarin', 'Mandarín'),
        ('mien', 'Mien'),
        ('shanghainese', 'Shanghainés*'),
        ('taiwanese', 'Taiwanés'),
        ('taishanese', 'Taishanés'),
    )),
    ('South Pacific', (
        ('fijian', 'Fiyiano'),
        ('palauan', 'Palauano*'),
        ('samoan', 'Samoano'),
        ('tongan', 'Tongano'),
    )),
    ('Philippines', (
        ('bikol', 'Bicol'),
        ('cebuano', 'Cebuano'),
        ('ilocano', 'Ilocano'),
        ('ilongo', 'Ilonggo'),
        ('pampangan', 'Pampango'),
        ('pangasinan', 'Pangasinán'),
        ('tagalog', 'Tagalo'),
        ('visayan', 'Visayan'),
    )),
    ('Idiomas y Servicios Adicionales', (
        ('american_sign_language', 'Lenguaje de Señas Estadounidense'),
        ('braille', 'Braille'),
        ('esperanto', 'Esperanto'),
        ('latin', 'Latín'),
        ('phonetic', 'Fonético'),
        ('real_time_captioning', 'Subtitulación en tiempo real y remota'),
        ('tactile', 'Táctil'),
        ('limited_resources', 'Recursos Limitados Disponibles'),
    )),
)
# ○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○#
# ○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○#
#         Niveles de usuarios
Niveles_Usuarios = (

    ('Nivel 1', (
        ('Invitado', 'Invitado'),
    )),
    ('Nivel 2', (
        ('Registrado', 'Registrado'),
    )),
    ('Nivel 3', (
        ('Colaborador', 'Colaborador'),
    )),
    ('Sin nivel', 'Sin nivel'),
)